#!/bin/bash
# Test script for Gemini Advanced commands

echo "🧪 Testing Gemini Advanced Commands"
echo "===================================="
echo ""
echo "This script will help you test if the commands work inside Gemini CLI."
echo ""
echo "1. First, open a new terminal to load the updated configuration"
echo "2. Run 'gemini' to start the Gemini CLI"
echo "3. Inside Gemini CLI, try these commands:"
echo ""
echo "Test Commands:"
echo "--------------"
echo "g.help                           # Should show command list"
echo "g what is Docker                 # Standard response"
echo "gt explain async programming     # Think mode - detailed"
echo "gth analyze OAuth2 security      # Think hard - critical analysis"
echo "gu design payment system         # Ultra think - exhaustive"
echo "g.arch microservices vs monolith # Architect perspective"
echo "g.debug API returns 500 errors   # Debugging approach"
echo "g.teach explain closures         # Teaching style"
echo ""
echo "Expected Behavior:"
echo "-----------------"
echo "- g.help should always show the help menu"
echo "- Different commands should produce different depth/style responses"
echo "- Personas should approach problems from their perspective"
echo ""
echo "Troubleshooting:"
echo "---------------"
echo "If commands don't work:"
echo "1. Check extension is loaded: ls ~/.gemini/extensions/"
echo "2. Restart terminal and Gemini CLI"
echo "3. Try 'gemini --help' to see available options"
echo ""